package com.a9ae0b01f0ffc.emb.main

import com.a9ae0b01f0ffc.commons.main.T_common_commons


class T_emb_commons extends T_common_commons{

    String GC_TPN_CLASSES_CONF
    String GC_BLACK_BOX_CONFIG
    String GC_SOURCE_FILE_NAME
    String GC_DESTINATION_FILE_NAME
    String GC_EMB_CSV_SEPARATOR
    String GC_CSV_NAME_ON_CARD_FIELD_NUMBER
    String GC_CSV_TRACK_1_FIELD_NUMBER
    String GC_TRACK_1_DEFAULT_NAME
    String GC_EMPTY_NAME_REPLACEMENT_1
    String GC_EMPTY_NAME_REPLACEMENT_2
    String GC_EMPTY_NAME_REPLACEMENT_3
    String GC_EMPTY_NAME_REPLACEMENT_4
    String GC_EMPTY_NAME_REPLACEMENT_5
    String GC_TRACK_1_NAME_SEPARATOR

    T_emb_commons(String i_conf_file_name) {
        super(i_conf_file_name)
        GC_TPN_CLASSES_CONF = GC_CONST_CONF.GC_TPN_CLASSES_CONF(GC_TPN_CLASSES_CONF)
        GC_BLACK_BOX_CONFIG = GC_CONST_CONF.GC_BLACK_BOX_CONFIG(GC_BLACK_BOX_CONFIG)
        GC_SOURCE_FILE_NAME = GC_CONST_CONF.GC_SOURCE_FILE_NAME(GC_SOURCE_FILE_NAME)
        GC_DESTINATION_FILE_NAME = GC_CONST_CONF.GC_DESTINATION_FILE_NAME(GC_DESTINATION_FILE_NAME)
        GC_EMB_CSV_SEPARATOR = GC_CONST_CONF.GC_EMB_CSV_SEPARATOR(GC_EMB_CSV_SEPARATOR)
        GC_CSV_NAME_ON_CARD_FIELD_NUMBER = GC_CONST_CONF.GC_CSV_NAME_ON_CARD_FIELD_NUMBER(GC_CSV_NAME_ON_CARD_FIELD_NUMBER)
        GC_CSV_TRACK_1_FIELD_NUMBER = GC_CONST_CONF.GC_CSV_TRACK_1_FIELD_NUMBER(GC_CSV_TRACK_1_FIELD_NUMBER)
        GC_TRACK_1_DEFAULT_NAME = GC_CONST_CONF.GC_TRACK_1_DEFAULT_NAME(GC_TRACK_1_DEFAULT_NAME)
        GC_EMPTY_NAME_REPLACEMENT_1 = GC_CONST_CONF.GC_EMPTY_NAME_REPLACEMENT_1(GC_EMPTY_NAME_REPLACEMENT_1)
        GC_EMPTY_NAME_REPLACEMENT_2 = GC_CONST_CONF.GC_EMPTY_NAME_REPLACEMENT_2(GC_EMPTY_NAME_REPLACEMENT_2)
        GC_EMPTY_NAME_REPLACEMENT_3 = GC_CONST_CONF.GC_EMPTY_NAME_REPLACEMENT_3(GC_EMPTY_NAME_REPLACEMENT_3)
        GC_EMPTY_NAME_REPLACEMENT_4 = GC_CONST_CONF.GC_EMPTY_NAME_REPLACEMENT_4(GC_EMPTY_NAME_REPLACEMENT_4)
        GC_EMPTY_NAME_REPLACEMENT_5 = GC_CONST_CONF.GC_EMPTY_NAME_REPLACEMENT_5(GC_EMPTY_NAME_REPLACEMENT_5)
        GC_TRACK_1_NAME_SEPARATOR = GC_CONST_CONF.GC_TRACK_1_NAME_SEPARATOR(GC_TRACK_1_NAME_SEPARATOR)
    }

}
